# Numpy

Numpy or(NumPy)is a Linear Algebra Library in Python that is used in Data science.Numpy has many capabilities,I will not write all of them but I mentiones most of the codes that are used in Data science field.important aspects of Numpy consist of vectors,arrays,matrices, and last but not least number generation that are coverd in this notebook.

Source:Udemy.com

# Creating a Numpy Array

In [3]:
import numpy as np

In [4]:
my_list=[1,2,3,4,5,6,7,9,12]

In [5]:
np.array(my_list)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 12])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built_in Methods

There are lots of built_in method in Numpy library to generate array

# Range and Arange

In [8]:
list(range(1,75,6))

[1, 7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73]

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

# Zeros and One

# Make a Zero 

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Make a One

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Linespace

linespace can help us to provide evenly spaced numbers over a specified interval

In [14]:
np.linspace(1,40,100)

array([ 1.        ,  1.39393939,  1.78787879,  2.18181818,  2.57575758,
        2.96969697,  3.36363636,  3.75757576,  4.15151515,  4.54545455,
        4.93939394,  5.33333333,  5.72727273,  6.12121212,  6.51515152,
        6.90909091,  7.3030303 ,  7.6969697 ,  8.09090909,  8.48484848,
        8.87878788,  9.27272727,  9.66666667, 10.06060606, 10.45454545,
       10.84848485, 11.24242424, 11.63636364, 12.03030303, 12.42424242,
       12.81818182, 13.21212121, 13.60606061, 14.        , 14.39393939,
       14.78787879, 15.18181818, 15.57575758, 15.96969697, 16.36363636,
       16.75757576, 17.15151515, 17.54545455, 17.93939394, 18.33333333,
       18.72727273, 19.12121212, 19.51515152, 19.90909091, 20.3030303 ,
       20.6969697 , 21.09090909, 21.48484848, 21.87878788, 22.27272727,
       22.66666667, 23.06060606, 23.45454545, 23.84848485, 24.24242424,
       24.63636364, 25.03030303, 25.42424242, 25.81818182, 26.21212121,
       26.60606061, 27.        , 27.39393939, 27.78787879, 28.18

# eye

We can create indentity matrix with eye

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random

In [ ]:
Numpy library has many abilities for making random matrix

# Rand

In [14]:
np.random.rand(5,4)

array([[0.36101582, 0.35407544, 0.09898017, 0.35256371],
       [0.0355349 , 0.44399541, 0.38899497, 0.25982693],
       [0.28827461, 0.55960179, 0.7327993 , 0.92689666],
       [0.29924185, 0.13177633, 0.29887648, 0.2953528 ],
       [0.89620231, 0.31834684, 0.27178279, 0.25930392]])

# Randn

In [ ]:
Return the "Standard normal distribution"

In [19]:
np.random.randn(5,9)

array([[ 1.85879497,  0.21451643,  0.3588958 , -1.05640352, -0.09829853,
        -0.23135396, -0.49713786, -0.09195867,  0.40205678],
       [-0.59597878,  0.20086723, -0.11397386, -1.09248928,  0.16014191,
         1.62350963,  1.1347145 , -0.98687223,  0.43792337],
       [-0.46899014,  0.69948522, -0.13857587, -1.82343825, -1.0587951 ,
         0.22576067,  0.34190326, -0.36462583,  0.02087617],
       [ 0.53550785, -0.65448984, -1.54982849, -1.26626121,  0.050364  ,
         0.6658052 ,  1.45004664, -0.65317203, -0.321064  ],
       [-0.38486501,  0.97639365, -0.83957408,  0.81205986, -0.32273117,
        -0.50380075,  0.15366055, -0.94023108,  1.7059416 ]])

In [20]:
np.random.randint(1,200,30)

array([ 48, 164,  60,  60,  85,  97, 126, 188, 127,  53,  13, 100, 196,
        37,  93,  71, 173,  60,  42, 119,  99,  29, 167,  37, 138, 142,
       153,   2, 134,  49])

In [34]:
arr=np.arange(25)

# Reshape

We can change the shape of the array with reshape code in Numpy

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Randint

In [ ]:
Numpy library has ability to return random integare from low to high

In [37]:
randarr=np.random.randint(100,300,50)

In [38]:
randarr

array([163, 256, 265, 101, 131, 296, 178, 251, 245, 131, 156, 183, 280,
       270, 185, 141, 146, 204, 193, 205, 130, 270, 247, 105, 213, 208,
       277, 140, 157, 253, 136, 143, 121, 196, 129, 297, 275, 122, 240,
       277, 277, 178, 221, 211, 135, 173, 159, 296, 245, 163])

In [39]:
randarr.reshape(5,10)

array([[163, 256, 265, 101, 131, 296, 178, 251, 245, 131],
       [156, 183, 280, 270, 185, 141, 146, 204, 193, 205],
       [130, 270, 247, 105, 213, 208, 277, 140, 157, 253],
       [136, 143, 121, 196, 129, 297, 275, 122, 240, 277],
       [277, 178, 221, 211, 135, 173, 159, 296, 245, 163]])

# max,min,argmax,argmin

with simple code we can find max,min and max and min location easily in numpy library

In [22]:
randarr.max()

99

In [23]:
randarr.min()

0

In [24]:
randarr.argmax()

28

In [25]:
randarr.argmin()

20

# Slicing and Endexing

The easiest way to pick one or more elemnts of an array

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [27]:
arr[3]

4

In [28]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25])

In [29]:
arr[:3]

array([1, 2, 3])

In [30]:
arr_copy=arr.copy()

In [31]:
arr_copy[:3]=400

In [32]:
arr_copy

array([400, 400, 400,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25])

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [35]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [36]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2d[1,1]

25

In [39]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2d[2:,:]

array([[35, 40, 45]])

# Selection

We can select array based on comparison operation

In [7]:
import numpy as np

In [8]:
arr=np.arange(0,11,2)

In [11]:
bool_arr=arr[arr>5]

In [12]:
bool_arr

array([ 6,  8, 10])

In [13]:
arr[arr<3]

array([0, 2])

In [14]:
x=4
arr[arr>x]

array([ 6,  8, 10])

In [15]:
arr+arr

array([ 0,  4,  8, 12, 16, 20])

In [16]:
arr-arr

array([0, 0, 0, 0, 0, 0])

In [17]:
arr*arr

array([  0,   4,  16,  36,  64, 100])

In [18]:
arr/arr

C:\Users\Ansari\AppData\Local\Temp\ipykernel_2568\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.])

In [19]:
1/arr

C:\Users\Ansari\AppData\Local\Temp\ipykernel_2568\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 0.5       , 0.25      , 0.16666667, 0.125     ,
       0.1       ])